# Generated by Django 2.2 on 2019-04-09 10:37

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('contents', models.TextField()),
                ('price', models.FloatField()),
                ('score', models.CharField(choices=[('ONE', '별 1개'), ('TWO', '별 2개'), ('THREE', '별 3개'), ('FOUR', '별 4개'), ('FIVE', '별 5개')], max_length=5)),
                ('created_date', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
    ]
